services:
  checkmate-app:
    build: .
    ports:
      - "4200:4200"
    volumes:
      # Sincroniza el código local con el contenedor
      - .:/app
      # Evita que node_modules local sobreescriba al del contenedor
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true